name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          conda install numpy
          conda install -c conda-forge igl
          python -m pip install polyscope
          conda install -c conda-forge scikit-sparse
      - name: Run tests with pytest
        run: python -m unittest
